# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_BQ2589X_CHARGER)	+= bq2589x_chg_mmi/
obj-$(CONFIG_SGM4154X_CHARGER)	+= sgm4154x_chg_mmi/
